global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: zookeeper
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["zookeeper:2181"]

  - job_name: kafka
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: kafka-schema-registry
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["kafka-schema-registry:8081"]

  - job_name: kafka-connect
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["kafka-connect:8083"]
